//
//  AllMagic.inc
//
//  Created by Kangming Yu on 5/17/22.
//

#include "Game/Magic/BaseMagic.hpp"

#include "Game/Magic/StoneBlast.hpp"            // STONEBLAST = 0
#include "Game/Magic/FireBall.hpp"              // FIREBALL = 1
#include "Game/Magic/LightningPhalanx.hpp"      // LIGHTNINGSPEAR = 2
#include "Game/Magic/GroundSmash.hpp"           // GROUNDSMASH = 3
#include "Game/Magic/Thunder.hpp"               // THUNDER = 4
#include "Game/Magic/Flame.hpp"                 // FLAME = 5
#include "Game/Magic/ThousandBlade.hpp"         // THOUSANDBLADE = 6
#include "Game/Magic/DragonMagic.hpp"           // DRAGON = 7
